name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Install build essentials and CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Install Vulkan SDK
      run: sudo apt-get install -y libvulkan-dev
        
    - name: Install Qt
      run: sudo apt-get install -y qtbase5-dev

    - name: Configure
      run: cmake -B build
    
    - name: Build
      run: cmake --build build

  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Install Chocolatey packages
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install visualstudio2019community
        choco install visualstudio2019-workload-vctools
        choco install vulkansdk
        
    - name: Install Qt
      run: choco install qt-opensource-windows-x86-mingw530-5.7.0

    - name: Configure
      run: cmake -B build
    
    - name: Build
      run: cmake --build build
