name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libvulkan-dev qt5-default
        
    - name: Configure
      run: cmake -B build
    
    - name: Build
      run: cmake --build build

  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Install dependencies
      run: |
        choco install cmake --version=3.22.1
        choco install vulkansdk
        choco install qt5
        
    - name: Configure
      run: cmake -B build
    
    - name: Build
      run: cmake --build build
