name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Set up C++ environment
      uses: actions/setup-cpp@v2
      with:
        compiler: gcc
        cmake-version: '3.22.x'
        
    - name: Install Vulkan SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y libvulkan-dev
        
    - name: Install Qt
      run: sudo apt-get install -y qt5-default

    - name: Configure
      run: cmake -B build
    
    - name: Build
      run: cmake --build build

  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Set up C++ environment
      uses: actions/setup-cpp@v2
      with:
        cmake-version: '3.22.x'
        
    - name: Install Vulkan SDK
      run: choco install vulkansdk

    - name: Install Qt
      run: choco install qt5

    - name: Configure
      run: cmake -B build
    
    - name: Build
      run: cmake --build build
