name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      
    steps:
    - name: Ensure Git is installed
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Set up C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake make
        
    - name: Install Vulkan SDK
      run: sudo apt-get install -y libvulkan-dev
        
    - name: Install Qt and dependencies
      run: sudo apt-get install -y qtbase5-dev qttools5-dev-tools

    - name: Configure
      run: cmake -B build
    
    - name: Build
      run: cmake --build build

  build-windows:
    runs-on: windows-latest

  - name: Ensure Git is installed
    run: |
      choco install git
      $env:PATH += ";C:\Program Files\Git\cmd"
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Set up C++ environment
      run: |
        choco install -y visualstudio2019buildtools
        choco install -y visualstudio2019-workload-vctools
        
    - name: Install Vulkan SDK
      run: |
        $url = "https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe?u="
        $output = "vulkan-sdk.exe"
        Invoke-WebRequest -Uri $url -OutFile $output
        Start-Process -Wait -FilePath $output

    - name: Install Qt
      run: |
        pip install aqtinstall
        python -m aqt install --outputdir C:\Qt 5.15.2 windows desktop win64_msvc2019_64 -m qttools

    - name: Configure
      run: cmake -B build -DCMAKE_PREFIX_PATH=C:\Qt\5.15.2\msvc2019_64
    
    - name: Build
      run: cmake --build build
